permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM

# 作者信息
author: 
  name: Guo Yanhao
  email: guoyanhao2008@gmail.com
  link: http://blog.iblackdev.com
  weibo: http://weibo.com/iblackdev
  github: http://github.com/iblackdev

# 站点信息
title: iBlackDev
description: iBalackDev的博客
url: http://blog.iblackdev.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /assets/img/avatar.jpg
favicon: 

# google analytics 设置
# ga:
#   id: 
#   url: 

# disqus 设置
# disqus:
#   shortname: 